### PR TITLE
Update to v1.2.6

### PR DESCRIPTION
**Pull request by fopina**
This comes after https://github.com/surface-security/scanner-httpx/issues/19 and tree is back to being shared with upstream httpx

`temporary_redo` branch is the tree re-done as v1.1.2. This PR is to upgrade it (`main` after rename) to latest (1.2.6)

### CODE REVIEW

**Comment by gsilvapt** [comment]
There are some errors in the build process. Perhaps related to `go version`?

**Comment by fopina** [comment]
Maybe.. to revisit once (if) temporary_redo is made into main

**Comment by gsilvapt** [comment]
> Maybe.. to revisit once (if) temporary_redo is made into main

So, we have to proceed with the failed build, that's expected?

**Comment by fopina** [comment]
This updated one (1.2.6) is failing, but I meant the other one. Or is that one falling builds as well? I think the actions did not run on it

**Comment by fopina** [comment]
Confirmed that build works in `temporary_redo` with #20

That's what I meant: looking into this PR after confirming will be renaming temporary_redo to main :)

**Comment by fopina** [comment]
Build fixed ✅

**Comment by gsilvapt** [comment]
> Build fixed white_check_mark

I think it's failing because of `go mod download`. Something quite strange happening there :sweat_smile:

**Comment by fopina** [comment]
Yeah just re-ran the build and it worked now

**Comment by fopina** [comment]
Converting to draft so the merge is re-done after `dev-112` is made into main (in case squashing still changes there)

**Comment by fopina** [comment]
superseded by #22

**Pull request closed without merging**
